FROM alpine:latest

ENV USERPROFILE=C:\Users\xxx
ENV DOCKER_CERT_PATH=${USERPROFILE}\.docker\machine\machines\default
ENV DOCKER_HOST=tcp://192.168.99.100
ENV DOCKER_MACHINE_NAME=default
ENV DOCKER_TLS_VERIFY=1
